name: Deploy Frontend to S3
on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: proptech-frontend-app
  BUILD_DIR: dist
  NODE_VERSION: "20"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::048643934642:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify caller
        run: aws sts get-caller-identity

      # 1) Upload hashed/static assets with a long cache
      - name: Sync assets (immutable)
        run: |
          aws s3 sync "$BUILD_DIR" "s3://${S3_BUCKET}" \
            --delete \
            --exclude "index.html" \
            --exclude "*.html" \
            --cache-control "public,max-age=31536000,immutable"

      # 2) Upload HTML entry points with no-cache (so deploys go live immediately)
      - name: Upload HTML (no-cache)
        run: |
          find "$BUILD_DIR" -name "*.html" -print0 | xargs -0 -I {} \
            aws s3 cp "{}" "s3://${S3_BUCKET}/$(realpath "{}")" \
              --cache-control "no-cache, no-store, must-revalidate" \
              --content-type "text/html; charset=utf-8"
