name: Deploy Frontend to S3
on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: proptech-frontend-app
  BUILD_DIR: dist
  NODE_VERSION: "20"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::048643934642:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify caller
        run: aws sts get-caller-identity

      # Upload the distribution files
      - name: Sync assets (immutable)
        run: |
          aws s3 sync "$BUILD_DIR" "s3://${S3_BUCKET}" \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
      
      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EHX16SDASR089 \
            --paths "/index.html"
           
